// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMITMENT_H_
#define FLATBUFFERS_GENERATED_COMMITMENT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

struct Sigma;
struct SigmaBuilder;
struct SigmaT;

inline const ::flatbuffers::TypeTable *SigmaTypeTable();

struct SigmaT : public ::flatbuffers::NativeTable {
  typedef Sigma TableType;
  std::vector<std::string> curve_name{};
  std::vector<std::string> postulate_coordinate{};
  std::vector<std::string> commitment_coordinate{};
};

struct Sigma FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SigmaT NativeTableType;
  typedef SigmaBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SigmaTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CURVE_NAME = 4,
    VT_POSTULATE_COORDINATE = 6,
    VT_COMMITMENT_COORDINATE = 8
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *curve_name() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_CURVE_NAME);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *mutable_curve_name() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_CURVE_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *postulate_coordinate() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_POSTULATE_COORDINATE);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *mutable_postulate_coordinate() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_POSTULATE_COORDINATE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *commitment_coordinate() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_COMMITMENT_COORDINATE);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *mutable_commitment_coordinate() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_COMMITMENT_COORDINATE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CURVE_NAME) &&
           verifier.VerifyVector(curve_name()) &&
           verifier.VerifyVectorOfStrings(curve_name()) &&
           VerifyOffset(verifier, VT_POSTULATE_COORDINATE) &&
           verifier.VerifyVector(postulate_coordinate()) &&
           verifier.VerifyVectorOfStrings(postulate_coordinate()) &&
           VerifyOffset(verifier, VT_COMMITMENT_COORDINATE) &&
           verifier.VerifyVector(commitment_coordinate()) &&
           verifier.VerifyVectorOfStrings(commitment_coordinate()) &&
           verifier.EndTable();
  }
  SigmaT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SigmaT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Sigma> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SigmaT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SigmaBuilder {
  typedef Sigma Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_curve_name(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> curve_name) {
    fbb_.AddOffset(Sigma::VT_CURVE_NAME, curve_name);
  }
  void add_postulate_coordinate(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> postulate_coordinate) {
    fbb_.AddOffset(Sigma::VT_POSTULATE_COORDINATE, postulate_coordinate);
  }
  void add_commitment_coordinate(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> commitment_coordinate) {
    fbb_.AddOffset(Sigma::VT_COMMITMENT_COORDINATE, commitment_coordinate);
  }
  explicit SigmaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Sigma> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Sigma>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Sigma> CreateSigma(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> curve_name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> postulate_coordinate = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> commitment_coordinate = 0) {
  SigmaBuilder builder_(_fbb);
  builder_.add_commitment_coordinate(commitment_coordinate);
  builder_.add_postulate_coordinate(postulate_coordinate);
  builder_.add_curve_name(curve_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Sigma> CreateSigmaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *curve_name = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *postulate_coordinate = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *commitment_coordinate = nullptr) {
  auto curve_name__ = curve_name ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*curve_name) : 0;
  auto postulate_coordinate__ = postulate_coordinate ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*postulate_coordinate) : 0;
  auto commitment_coordinate__ = commitment_coordinate ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*commitment_coordinate) : 0;
  return CreateSigma(
      _fbb,
      curve_name__,
      postulate_coordinate__,
      commitment_coordinate__);
}

::flatbuffers::Offset<Sigma> CreateSigma(::flatbuffers::FlatBufferBuilder &_fbb, const SigmaT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline SigmaT *Sigma::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SigmaT>(new SigmaT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Sigma::UnPackTo(SigmaT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = curve_name(); if (_e) { _o->curve_name.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->curve_name[_i] = _e->Get(_i)->str(); } } else { _o->curve_name.resize(0); } }
  { auto _e = postulate_coordinate(); if (_e) { _o->postulate_coordinate.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->postulate_coordinate[_i] = _e->Get(_i)->str(); } } else { _o->postulate_coordinate.resize(0); } }
  { auto _e = commitment_coordinate(); if (_e) { _o->commitment_coordinate.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->commitment_coordinate[_i] = _e->Get(_i)->str(); } } else { _o->commitment_coordinate.resize(0); } }
}

inline ::flatbuffers::Offset<Sigma> Sigma::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SigmaT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSigma(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Sigma> CreateSigma(::flatbuffers::FlatBufferBuilder &_fbb, const SigmaT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SigmaT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _curve_name = _o->curve_name.size() ? _fbb.CreateVectorOfStrings(_o->curve_name) : 0;
  auto _postulate_coordinate = _o->postulate_coordinate.size() ? _fbb.CreateVectorOfStrings(_o->postulate_coordinate) : 0;
  auto _commitment_coordinate = _o->commitment_coordinate.size() ? _fbb.CreateVectorOfStrings(_o->commitment_coordinate) : 0;
  return CreateSigma(
      _fbb,
      _curve_name,
      _postulate_coordinate,
      _commitment_coordinate);
}

inline const ::flatbuffers::TypeTable *SigmaTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 1, -1 },
    { ::flatbuffers::ET_STRING, 1, -1 },
    { ::flatbuffers::ET_STRING, 1, -1 }
  };
  static const char * const names[] = {
    "curve_name",
    "postulate_coordinate",
    "commitment_coordinate"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 3, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const Sigma *GetSigma(const void *buf) {
  return ::flatbuffers::GetRoot<Sigma>(buf);
}

inline const Sigma *GetSizePrefixedSigma(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Sigma>(buf);
}

inline Sigma *GetMutableSigma(void *buf) {
  return ::flatbuffers::GetMutableRoot<Sigma>(buf);
}

inline Sigma *GetMutableSizePrefixedSigma(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<Sigma>(buf);
}

inline bool VerifySigmaBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Sigma>(nullptr);
}

inline bool VerifySizePrefixedSigmaBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Sigma>(nullptr);
}

inline void FinishSigmaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Sigma> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSigmaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Sigma> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<SigmaT> UnPackSigma(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SigmaT>(GetSigma(buf)->UnPack(res));
}

inline std::unique_ptr<SigmaT> UnPackSizePrefixedSigma(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SigmaT>(GetSizePrefixedSigma(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_COMMITMENT_H_
